(defproject sweet-tooth-todo-example "0.1.0-SNAPSHOT"
  :description "a sweet little todo example"
  :min-lein-version "2.0.0"

  :plugins [[duct/lein-duct "0.12.1"]
            [lein-tools-deps "0.4.5"]]

  :lein-tools-deps/config {:config-files [:install :user :project]
                           :aliases      [:backend :dev]}

  :resource-paths ["resources" "target/resources"]
  :middleware     [lein-duct.plugin/middleware
                   lein-tools-deps.plugin/resolve-dependencies-with-deps-edn]

  :target-path    "target/%s/"
  :main           ^:skip-aot sweet-tooth.todo-example.backend.core

  :profiles
  {;; generated by duct
   :dev          [:project/dev :profiles/dev]
   :repl         {:repl-options {:init-ns user}}
   :uberjar      {:aot :all}
   :profiles/dev {}
   :project/dev  {:source-paths   ["dev/src"]
                  :resource-paths ["dev/resources" "target/dev/resources"]
                  :target-path    "target/dev/"
                  :dependencies   [[integrant/repl "0.3.1"]
                                   [eftest "0.5.4"]
                                   [kerodon "0.9.0"]
                                   [com.gfredericks/test.chuck "0.2.7"]
                                   [reifyhealth/specmonstah "2.0.0"]
                                   [test2junit "1.4.2"]]
                  :plugins        [[test2junit "1.4.2"]]

                  :test2junit-output-dir ".out/test-results"}

   :local-staging {:target-path    "target/local-staging/"
                   :resource-paths ["dev/resources" "frontend-target/local-staging"]}
   :staging       {:target-path            "target/staging/"
                   :resource-paths         ["dev/resources" "frontend-target/staging"]
                   :lein-tools-deps/config {:aliases ^:replace [:backend]}}
   :prod          {:target-path            "target/prod/"
                   :resource-paths         ["frontend-target/prod"]
                   :lein-tools-deps/config {:aliases ^:replace [:backend]}}

   :test {:resource-paths         ["dev/resources" "frontend-target/test"]
          :lein-tools-deps/config {:aliases [:test]}}})
